version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "80:80"
        volumes:
            - './:/var/www/app'
        depends_on:
            - php

    frontend:
        build:
            context: .
            dockerfile: docker/frontend/Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - './frontend:/var/www/app'

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - './:/var/www/app'
        expose:
            - 9001
        depends_on:
            - postgresql
        extra_hosts:
            - "host.docker.internal:host-gateway"

    postgresql:
        build:
            context: .
            dockerfile: docker/postgresql/Dockerfile
        ports:
            - "5432:5432"
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - pgdata-local:/var/lib/postgresql/data
        env_file:
            - .env

volumes:
    pgdata-local:
